#ifndef __MT7697_MICROPYTHON_MACHINE_RTC_H__
#define __MT7697_MICROPYTHON_MACHINE_RTC_H__

#define _RTC_BASE_YEAR 2000
#define _RTC_DEFAULT_YEAR  2019
#define _RTC_DEFAULT_MON   1
#define _RTC_DEFAULT_DAY   1
#define _RTC_DEFAULT_HOUR  0
#define _RTC_DEFAULT_MIN   0
#define _RTC_DEFAULT_SEC   0

#endif 
